[en]
  title = "Blog"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[hu]
  title = "Blog"
  languageName = "Magyar"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/hu"
